version: '{branch}.{build}'
branches:
  only:
  - php72_appveyor

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.10
  matrix:
  - ARTIFACT_NAME: cairo_vc15_php7_%Platform%_ts.zip
    OUTDIR: Release_TS
    V8_ASSETS: cairo-1.14.6-%Platform%-vc15.zip
  - ARTIFACT_NAME: cairo_vc15_php7_%Platform%_nts.zip
    OUTDIR: Release
    CONFIGURE_EXTRA: --disable-zts
    V8_ASSETS: cairo-1.14.6-%Platform%-vc15.zip

  PHP_VERSION: 7.2.0RC2
  PHP_SDK: c:\projects\php-sdk

image: Visual Studio 2017
clone_folder: c:\projects\php-sdk\cairo-ci\vc15\%Platform%\php\ext\cairo

platform:
  - x64
  - x86

install:
  - cmd: cinst wget
  - cd
  - for /R %%f in (*.phpt) do perl -pi.bak -e "undef $/; s/--EXTENSIONS--\neos_datastructures\n//gi" %%f
  - del *.phpt.bak /s > nul
  - wget https://github.com/OSTC/php-sdk-binary-tools/archive/%PHP_SDK_BINARY_TOOLS_VER%.zip --no-check-certificate -q -O php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip
  - 7z x -y php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip -oC:\projects
  - xcopy C:\projects\php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER% %PHP_SDK%\ /s > nul
  - cd %PHP_SDK%
  - call %PHP_SDK%\bin\phpsdk_setvars.bat
  - call %PHP_SDK%\bin\phpsdk_buildtree.bat cairo-ci
  - cd cairo-ci\vc15\%Platform%
  - if not exist php mkdir php
  - if not exist php\ext mkdir php\ext
  - cd php\ext
  - git clone https://github.com/eosforphp/datastructures.git eos_datastructures
  - cd ..\..
  - md deps
  - cd deps
  - curl -fSL -o %V8_ASSETS% "https://phpdev.toolsforresearch.com/%V8_ASSETS%"
  - 7z.exe x %V8_ASSETS%
  - cd ..
  - curl -fSL -o "php-%PHP_VERSION%-src.zip" "http://windows.php.net/downloads/qa/php-%PHP_VERSION%-src.zip"
  - ren php php-%PHP_VERSION%-src
  - 7z.exe x php-%PHP_VERSION%-src.zip | find /v "Extracting"
  - cd php-%PHP_VERSION%-src
  - cd
  - mkdir %OUTDIR%
  - mkdir \projects\%OUTDIR%
  - xcopy ..\deps\bin\*.dll \projects\%OUTDIR%\
  - move ..\deps\bin\*.dll %OUTDIR%\

build_script:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:VCVARS_PLATFORM="x86"
        $env:ENV_PLATFORM="x86"
      } Else {
        $env:VCVARS_PLATFORM="amd64"
        $env:ENV_PLATFORM="x64"
      }
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ENV_PLATFORM%
  - echo Building PHP [%PHP_VERSION%]
  - '%PHP_SDK%\bin\phpsdk_setvars'
  - buildconf
  - configure --disable-all --enable-cli --enable-zlib --enable-eos_datastructures=shared --with-cairo=shared --with-prefix=C:\projects\%OUTDIR% %CONFIGURE_EXTRA%
  - nmake
  - nmake install
  - cd C:\projects\%OUTDIR%
  - cd
  - echo [PHP] > php.ini
  - echo extension_dir = "ext" >> php.ini
  - echo extension=php_eos_datastructures.dll >> php.ini
  - echo extension=php_cairo.dll >> php.ini
  - set TEST_PHP_EXECUTABLE=%cd%\php.exe
  - php -v
  - php -m
  - dir
  - dir ext
test_script:
- cmd: php.exe /projects/php-sdk/cairo-ci/vc15/%Platform%/php-%PHP_VERSION%-src/run-tests.php /projects/php-sdk/cairo-ci/vc15/%Platform%/php-%PHP_VERSION%-src/ext/cairo -q --show-diff

on_finish:
  - 7z a -r %ARTIFACT_NAME% *
  - ps: Push-AppveyorArtifact $env:ARTIFACT_NAME

deploy:
